name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Setup environment
        run: cp .env.example .env.production
      
      - name: Install dependencies
        run: bun install
      
      - name: Build static site
        run: |
          # Skip the Prisma database operations
          # Just build the Next.js app for static deployment
          bun run next build
          bun run next export
        env:
          NEXT_PUBLIC_BASE_PATH: /etherguild
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages