name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Setup environment
        run: cp .env.example .env.production
      
      - name: Install dependencies
        run: bun install
        
      - name: Install missing dependency
        run: bun add -d pino-pretty
      
      - name: Configure Next.js for static export
        run: |
          echo 'module.exports = { output: "export" }' > next.config.mjs
      
      - name: Build static site
        run: bun run next build
        env:
          NEXT_PUBLIC_BASE_PATH: /etherguild
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages